// Package baseline generates the reviewed routed-network operating system
// configuration used by a SentinelBox appliance.
package baseline

import (
	"fmt"
	"io/fs"
	"net"
	"net/netip"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"github.com/TBG-Chance/SentinelBox/internal/config"
)

const (
	FilterFamily = "inet"
	FilterTable  = "sentinelbox_filter"
	NATFamily    = "ip"
	NATTable     = "sentinelbox_nat"
)

// File is one generated file relative to an operator-selected staging root.
type File struct {
	Path     string
	Mode     fs.FileMode
	Contents []byte
}

// Bundle is a complete routed-mode baseline.
type Bundle []File

// Generate builds a deterministic baseline without changing the host.
func Generate(cfg config.Config) (Bundle, error) {
	if err := cfg.Validate(); err != nil {
		return nil, err
	}
	if !cfg.Network.Enabled {
		return nil, fmt.Errorf("network.enabled must be true to generate a routed baseline")
	}

	prefix, err := netip.ParsePrefix(cfg.Network.LANAddress)
	if err != nil {
		return nil, fmt.Errorf("parse LAN address: %w", err)
	}

	bundle := Bundle{
		{
			Path: "etc/systemd/network/10-sentinelbox-wan.network",
			Mode: 0o644,
			Contents: []byte(fmt.Sprintf(`[Match]
Name=%s

[Network]
DHCP=ipv4
IPv6AcceptRA=no
LinkLocalAddressing=no
`, cfg.Network.WANInterface)),
		},
		{
			Path: "etc/systemd/network/20-sentinelbox-lan.network",
			Mode: 0o644,
			Contents: []byte(fmt.Sprintf(`[Match]
Name=%s

[Network]
Address=%s
ConfigureWithoutCarrier=yes
IPv6AcceptRA=no
LinkLocalAddressing=no
`, cfg.Network.LANInterface, cfg.Network.LANAddress)),
		},
		{
			Path: "etc/sysctl.d/90-sentinelbox-forwarding.conf",
			Mode: 0o644,
			Contents: []byte(`# SentinelBox routed-mode forwarding policy
net.ipv4.ip_forward=1
net.ipv6.conf.all.forwarding=0
net.ipv6.conf.default.forwarding=0
`),
		},
		{
			Path:     "etc/nftables.d/sentinelbox.nft",
			Mode:     0o640,
			Contents: []byte(Ruleset(cfg.Network, cfg.DHCP.Enabled)),
		},
	}

	if cfg.DHCP.Enabled {
		mask := net.IP(net.CIDRMask(prefix.Bits(), 32)).String()
		bundle = append(bundle, File{
			Path: "etc/dnsmasq.d/sentinelbox.conf",
			Mode: 0o644,
			Contents: []byte(fmt.Sprintf(`# SentinelBox LAN-only DHCP and DNS
interface=%s
bind-dynamic
domain-needed
bogus-priv
stop-dns-rebind
dhcp-range=%s,%s,%s,%s
dhcp-option=option:router,%s
dhcp-option=option:dns-server,%s
`, cfg.Network.LANInterface, cfg.DHCP.RangeStart, cfg.DHCP.RangeEnd, mask,
				formatLease(cfg.DHCP.LeaseDuration.Duration), prefix.Addr(), prefix.Addr())),
		})
	}

	return bundle, nil
}

// Ruleset returns the SentinelBox-owned firewall and NAT tables. The policy
// permits DHCP/DNS on LAN and established or LAN-to-WAN routed IPv4 traffic.
// It does not expose the management API or permit IPv6 forwarding.
func Ruleset(networkConfig config.NetworkConfig, dhcpEnabled bool) string {
	wan := strconv.Quote(networkConfig.WANInterface)
	lan := strconv.Quote(networkConfig.LANInterface)
	prefix, _ := netip.ParsePrefix(networkConfig.LANAddress)
	subnet := prefix.Masked().String()

	var inputServices strings.Builder
	if dhcpEnabled {
		inputServices.WriteString(fmt.Sprintf("\t\tiifname %s udp dport 67 accept comment \"LAN DHCP\"\n", lan))
		inputServices.WriteString(fmt.Sprintf("\t\tiifname %s udp dport 53 accept comment \"LAN DNS\"\n", lan))
		inputServices.WriteString(fmt.Sprintf("\t\tiifname %s tcp dport 53 accept comment \"LAN DNS\"\n", lan))
	}

	return fmt.Sprintf(`# Generated by SentinelBox. Only these two tables are owned by SentinelBox.
table inet sentinelbox_filter {
	set sbox_watch {
		type ipv4_addr
		size 4096
	}

	set sbox_restricted {
		type ipv4_addr
		size 4096
	}

	set sbox_contained {
		type ipv4_addr
		size 4096
	}

	set sbox_trusted {
		type ipv4_addr
		size 4096
	}

	chain input {
		type filter hook input priority 0; policy drop;
		iifname "lo" accept
		ct state established,related accept
		iifname %s udp sport 67 udp dport 68 accept comment "WAN DHCP client"
%s		iifname %s ip protocol icmp accept comment "LAN IPv4 diagnostics"
	}

	chain forward {
		type filter hook forward priority 0; policy drop;
		ct state established,related accept
		iifname %s oifname %s ip saddr %s accept comment "LAN to WAN"
	}

	chain output {
		type filter hook output priority 0; policy accept;
	}
}

table ip sentinelbox_nat {
	chain postrouting {
		type nat hook postrouting priority 100; policy accept;
		oifname %s ip saddr %s masquerade
	}
}
`, wan, inputServices.String(), lan, lan, wan, subnet, wan, subnet)
}

// Write stages all generated files below root using atomic file replacement.
func (bundle Bundle) Write(root string) error {
	if !filepath.IsAbs(root) {
		return fmt.Errorf("staging output path must be absolute")
	}
	cleanRoot := filepath.Clean(root)
	for _, file := range bundle {
		relative := filepath.Clean(filepath.FromSlash(file.Path))
		if relative == "." || filepath.IsAbs(relative) || relative == ".." || strings.HasPrefix(relative, ".."+string(filepath.Separator)) {
			return fmt.Errorf("unsafe generated path %q", file.Path)
		}
		target := filepath.Join(cleanRoot, relative)
		if !strings.HasPrefix(target, cleanRoot+string(filepath.Separator)) {
			return fmt.Errorf("generated path escapes staging root: %q", file.Path)
		}
		if err := writeFileAtomically(target, file.Contents, file.Mode); err != nil {
			return fmt.Errorf("write %s: %w", file.Path, err)
		}
	}
	return nil
}

func writeFileAtomically(path string, contents []byte, mode fs.FileMode) error {
	directory := filepath.Dir(path)
	if err := os.MkdirAll(directory, 0o750); err != nil {
		return err
	}
	temporary, err := os.CreateTemp(directory, ".sentinelbox-*")
	if err != nil {
		return err
	}
	temporaryPath := temporary.Name()
	defer os.Remove(temporaryPath)

	if _, err := temporary.Write(contents); err != nil {
		temporary.Close()
		return err
	}
	if err := temporary.Sync(); err != nil {
		temporary.Close()
		return err
	}
	if err := temporary.Chmod(mode); err != nil {
		temporary.Close()
		return err
	}
	if err := temporary.Close(); err != nil {
		return err
	}
	return os.Rename(temporaryPath, path)
}

func formatLease(duration time.Duration) string {
	if duration%time.Hour == 0 {
		return fmt.Sprintf("%dh", int64(duration/time.Hour))
	}
	if duration%time.Minute == 0 {
		return fmt.Sprintf("%dm", int64(duration/time.Minute))
	}
	return fmt.Sprintf("%ds", int64(duration/time.Second))
}
